name = "kantoorinzicht"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "kantoorinzicht"
database_id = "8565fdcb-b598-4739-9f7f-2c9b456300f1"

[[r2_buckets]]
binding = "DOCS_BUCKET"
bucket_name = "kantoorinzicht-docs"

[triggers]
crons = ["0 3 1 * *"]
