import { chromium } from '@playwright/test';
const b = await chromium.launch({headless:true});
const p = await b.newPage();
p.on('console', m => console.log('[console]', m.type(), m.text().slice(0,300)));
p.on('request', r => { if(r.url().includes('/mna/')) console.log('[req]', r.method(), r.url().slice(0,120)); });
p.on('response', async r => { if(r.url().includes('/mna/document/upload')) console.log('[resp]', r.status(), (await r.text().catch(()=>'')).slice(0,400)); });
p.on('pageerror', e => console.log('[pageerror]', e.message));
await p.goto('https://koersvoormorgen.nl/mna.html');
await p.locator('#l-code').fill('I2N5JHZY');
await p.locator('#l-btn').click();
await p.waitForFunction(()=>window.S&&window.S.traject&&window.S.rol,null,{timeout:20000});
await p.evaluate(()=>{window.S.screen='main';window.S.fase=window.FASES.findIndex(f=>f.id==='financieel');window.renderApp();});
await p.waitForTimeout(2500);
const inp = p.locator('input[type="file"][multiple]');
console.log('inputs:', await inp.count());
await inp.first().setInputFiles(process.env.HOME+'/Desktop/testtrajecten-compleet/fysiopraktijk-de-beweging/02_Jaarrekening_2024_Fysiopraktijk_De_Beweging.pdf');
await p.waitForTimeout(60000);
console.log('DOCS financieel:', await p.evaluate(()=>JSON.stringify((window.DOCS.financieel||[]).map(d=>({n:d.naam,u:d.uploading,v:d.verworpen})))));
await b.close();
